import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oscar Herrera | Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/> 
      </head>
      
      <body className={inter.className}>
        <Theme accentColor="gray" grayColor="olive" radius="large" appearance="dark">
          {children}
        </Theme>
      </body>
    </html>
  );
}
