"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { useState } from "react";
import { ThemeContextProvider } from "./components/context/ThemeContext";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Oscar Herrera | Site",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let [theme, setTheme] = useState<"light" | "dark">("dark");
  

  return (
    <html lang="en" className="scroll-smooth">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/> 
      </head>
      
      <body className={inter.className}>
        <ThemeContextProvider value={{ theme, setTheme }}>
          <Theme hasBackground={true} accentColor="gray" grayColor="olive" radius="large" appearance={ theme }>
            {children}
            {/* <ThemePanel/> */}
          </Theme>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
